name: Rehearsal TS Upgrade (PROD)
on:
  workflow_dispatch:

jobs:
  test_action:
    name: Run Upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rehearsal-js/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: './test'
          pull-request-title: 'chore: compatibility for upcoming TypeScript {tsVersion}'
          pull-request-body: |
            ## Summary
            {summary}
            
            ## Fixed
            {fixedItems}
            
            ## To do
            {todoItems}
            
            ## Tests
            Only existing tests
